### ISSUE TITLE
Server Script Compile Error

### ISSUE THREAD

**Issue by spaniloj** [ineedbots/t4m_bot_warfare#1]
Everytime I try to run this mod I get a server script compile error. I have T4M installed so I'm not sure what I'm doing wrong.

1629727288 InitGame: \fs_game\mods/mp_bots\fxfrustumCutoff\1000\g_compassShowEnemies\0\g_gametype\sab\gamename\Call of Duty: World at War\mapname\mp_airfield\penetrationCount\5\protocol\101\r_watersim_enabled\1\shortversion\1\sv_allowAnonymous\0\sv_disableClientConsole\0\sv_floodprotect\4\sv_hostname\CoDWaWHost\sv_maxclients\24\sv_maxPing\0\sv_maxRate\5000\sv_minPing\0\sv_privateClients\0\sv_punkbuster\0\sv_pure\1\sv_voice\0\ui_maxclients\32\g_logTimeStampInSeconds\1
1629727289 ShutdownGame:
1629727289

**Comment by ForeskinJohn** [comment]
are you using lanfixed?

**Comment by whatcorey** [comment]
I'm getting the exact same issue, yes and using lanfixed

**Comment by whatcorey** [comment]
Any idea whats causing the error Ineedbots? Havn't been able to play this for months now

**Comment by ineedbots** [comment]
Use plutonium t4mp
