### ISSUE TITLE
Can you update to work with steam version again?

### ISSUE THREAD

**Issue by whatcorey** [ineedbots/t4m_bot_warfare#10]
The plutonium one is fine, however you cannot play offline at all due to limitations. Can you please update it to work with the steam version again? My internet is not the greatest, it worked perfectly before but now if you try playing on steam you will get a script error.

**Comment by JezuzLizard** [comment]
If you are using Steam version you need this installed: https://github.com/ineedbots/T4M

**Comment by whatcorey** [comment]
I am using t4m, it no longer works. you now get script compile errors

**Comment by ineedbots** [comment]
![image](https://user-images.githubusercontent.com/751729/203645584-0cedda8d-e6a1-4212-8de5-a3ce7220b2d8.png)
works fine... make sure you installed t4m
