### ISSUE TITLE
bot names

### ISSUE THREAD

**Issue by shakespearr** [ineedbots/t4m_bot_warfare#3]
is there any way to change bot names? like on iw5

**Comment by megvadulthangya** [comment]
botnames.txt 

to the mod folder maybe? Than place in the file:

Ivan Drago
James Bond
Noobkilla



etc

**Comment by shakespearr** [comment]
doesnt work for me

**Comment by megvadulthangya** [comment]
you using that main_shared folder structure?

I suggest create an iwd file (zip)for the main_shared folder starting with maps folder, so if you open your zip is the maps folder the first what you see) and place it in your mods/whatever folder And place the botnames.txt nearby your iwd.

**Comment by shakespearr** [comment]
none of that seems to be working for me, i know it can be done as some servers have renamed bots, i found the folder with the bot names: a,b,c,d,e ect... but when i changed them nothing happened.

**Comment by ineedbots** [comment]
you change the bots.txt

**Comment by EricTurner3** [comment]
Documenting for anyone else: for singleplayer WaW bot names, create a file named botnames.txt in %LOCALAPPDATA%\Activision\CodWaW\mods\mp_bots with a new username per line.
