### ISSUE TITLE
Bots not open the doors.

### ISSUE THREAD

**Issue by megvadulthangya** [ineedbots/t4m_bot_warfare#6]
For example the mp_lapatrouille map have several doors, which can open, can you add the option when bots stuck they try to USE-the USE button...? Maybe can solve this problem, this way without editing the waypoints...

**Comment by ineedbots** [comment]
Bot warfare was never designed to work with Frontlines Forever, just the vanilla game.

**Comment by megvadulthangya** [comment]
Ohhh... That thing is exist in the vanilla game... I make video about the problem to see yourself...

**Comment by megvadulthangya** [comment]
[https://youtu.be/q53__E90xvM](https://youtu.be/q53__E90xvM)

I guess you programmed the bots when they stuck they try to broke the glasses by PRESSING MELLE ATTACK... 

Can you add to that section, to randomly try to use the USE function? to open doors..

**Comment by ineedbots** [comment]
https://github.com/ineedbots/t4m_bot_warfare/commit/11f170073ce03386cab2a970547fa5048664d7b6#diff-fb80ce2e5ed0c26cdca5e41e6a9795d57a082cf4bc0d42aa58438324cd23fcf8R2053

fixed

**Comment by megvadulthangya** [comment]
You are a wizard! Thank you for your time!
