### ISSUE TITLE
Bots will not use the bridge located on Banzai.

### ISSUE THREAD

**Issue by Splormf** [ineedbots/t4m_bot_warfare#8]
Bots will not walk across the bridge on Banzai. This is a problem as there is both a headquarters on the bridge in headquarters mode, and a supply depot in search and destroy. Bots also will not move onto the bridge to use "revenge". Any help would be much appreciated, thank you!

**Comment by ineedbots** [comment]
https://github.com/ineedbots/t4m_bot_warfare/commit/fa835e7ff1d94f4ac3fde603423da4fc12e65dcc
fixed

**Comment by Splormf** [comment]
You are amazing, thank you so much!
